# Generated by Django 4.2.3 on 2024-06-09 08:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "modified",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[("apple", "Apple"), ("thinkpad", "Thinkpad")],
                        default="apple",
                        max_length=256,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "year_of_manufacture",
                    models.PositiveSmallIntegerField(
                        default=2024, verbose_name="Year of manufacture"
                    ),
                ),
                (
                    "ram",
                    models.PositiveSmallIntegerField(default=16, verbose_name="RAM"),
                ),
                (
                    "hdd_capacity",
                    models.PositiveIntegerField(
                        default=512, verbose_name="HDD capacity"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1500.00"),
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=10, verbose_name="Quantity"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
